"""response field is nonable do to avoid error

Revision ID: 9c4f7c3f9765
Revises: 1a74606b7a0b
Create Date: 2025-09-03 17:28:40.236768

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4f7c3f9765'
down_revision: Union[str, Sequence[str], None] = '1a74606b7a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatmessage', 'response',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatmessage', 'response',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
